server:
  port: 8300

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8282/realms/meter_data_app_realm/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/meter_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: "classpath:db/migrations"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: meterQueue
  exchange:
    name: meterTopicExchange
  routing:
    key: meterRoutingKey

keycloak:
  admin-username: admin
  admin-password: admin
  admin-realm: master
  admin-client-id: admin-cli
  realm: meter_data_app_realm
  roles: roles
  client-id: meter_data_app_client
  client-secret: 9P0UAOmvvj0G4BPtBD4wmvO1yvEVczcB
  auth-server-url: http://localhost:8282

springdoc:
  swagger-ui:
    oauth:
      client-id: meter_data_app_client
      client-secret: 9P0UAOmvvj0G4BPtBD4wmvO1yvEVczcB